wireguard_address: 10.0.0.1/24
wireguard_port: 51820

wireguard_peers:
  - name: macbook_pro_2019
    public_key: uxj44FV8bezZRgbkJicnAKiJesUebSzQKLii2Wi4WkQ=
    ip: 10.0.0.2/32
    
  - name: note_20_ultra
    public_key: mAbOEhoIZa/z2UGnW2ZyTX2/g9zYXRXctrwIVvWAsWI=
    ip: 10.0.0.3/32